fix resource reporting for devices without serial number

diff --git a/code/usb_actions/nuvlabox-add-usb-peripheral b/code/usb_actions/nuvlabox-add-usb-peripheral
--- a/code/usb_actions/nuvlabox-add-usb-peripheral
+++ b/code/usb_actions/nuvlabox-add-usb-peripheral
@@ -96,11 +96,10 @@ classes_final=$(echo "["${ordered_classes} | sed 's/,$/]/')
 disk_by_id="/dev/disk/by-id"
 
 resources=''
-if [ -n "$device_serial" ]
+if [[ -n "$device_serial" ]]
 then
   matching_usb_disks=$(ls -d ${disk_by_id}/* | grep usb | grep "${device_serial}")
   mounts=$(mount)
-  gb_in_bytes=1000000000
   for disk in ${matching_usb_disks}
   do
     block_device=$(readlink -f ${disk})
@@ -218,13 +217,15 @@ fi
 ########
 if [[ -z ${existing_peripheral_identifier} ]]
 then
-    echo "INFO: posting new peripheral to Nuvla: ${json}"
+    if [[ ! -f "${nuvlabox_peripheral_filename}" ]]
+    then
+      echo "INFO: posting new peripheral to Nuvla: ${json}"
 
-    (id=$(nuvla-client-post "nuvlabox-peripheral" "${json}") && \
-        nuvla_id=$(echo "${id}" | awk -F' ' '{print $NF}') && \
-        echo ${json} | jq --arg id "${nuvla_id}" '. + {id: $id}' > ${nuvlabox_peripheral_filename} && \
-        echo "INFO: successfully registered peripheral ${identifier}" ) || echo "ERR: could not register new USB device ${identifier}!"
-
+      (id=$(nuvla-client-post "nuvlabox-peripheral" "${json}") && \
+          nuvla_id=$(echo "${id}" | awk -F' ' '{print $NF}') && \
+          echo ${json} | jq --arg id "${nuvla_id}" '. + {id: $id}' > ${nuvlabox_peripheral_filename} && \
+          echo "INFO: successfully registered peripheral ${identifier}" ) || echo "ERR: could not register new USB device ${identifier}!"
+    fi
 else
     # existing_peripheral_identifier is set, meaning that this peripheral exists already, so this is an UPDATE
 
