detect delete 404

diff --git a/code/usb_actions/nuvla-client-delete b/code/usb_actions/nuvla-client-delete
--- a/code/usb_actions/nuvla-client-delete
+++ b/code/usb_actions/nuvla-client-delete
@@ -80,9 +80,22 @@ session_template='{
     -d "${session_template}" | jq -e '.status==201' &>/dev/null) || { echo "ERR: can not login to ${nuvla_endpoint}"; exit 1; }
 
 
-# Now we can push the resource
-(curl -XDELETE --fail \
-    ${nuvla_endpoint}/api/${resource_id} \
-    -H accept:application/json \
-    -b ${cookies_file} \
-    ${extra_flags} | jq -e '.status==200' &>/dev/null) || { echo "WARN: Cannot delete resource ${resource_id} in Nuvla"; exit 1; }
+# Now we can delete the resource
+status=$(curl -XDELETE \
+          ${nuvla_endpoint}/api/${resource_id} \
+          -H accept:application/json \
+          -b ${cookies_file} \
+          ${extra_flags} | jq -r '.status')
+
+
+if [[ $status -eq 200 ]]
+then
+    exit 0
+elif [[ $status -eq 404 ]]
+then
+    echo "INFO: ${resource_id} not found in Nuvla (404). Assuming it has already been deleted...moving on"
+    exit 0
+else
+    echo "WARN: Cannot delete resource ${resource_id} in Nuvla"
+    exit 1
+fi
