add workflow for peripheral update

diff --git a/code/usb_actions/nuvlabox-add-usb-peripheral b/code/usb_actions/nuvlabox-add-usb-peripheral
--- a/code/usb_actions/nuvlabox-add-usb-peripheral
+++ b/code/usb_actions/nuvlabox-add-usb-peripheral
@@ -10,6 +10,7 @@ buspath=$1
 devnumber=$2
 nb_id=$3
 nb_version=$4
+check_for_update=$5
 
 if [[ -z ${buspath} ]] || [[ -z ${devnumber} ]] || [[ -z ${nb_id} ]] || [[ -z ${nb_version} ]]
 then
@@ -104,56 +105,69 @@ add_string_json() {
     echo $1 | jq --arg newarg "${3}" --arg key "${2}" '. + {($key): $newarg}'
 }
 
-json=$( jq -n \
-            --arg parent "${nb_id}" \
-            --argjson version ${nb_version} \
-            --argjson available ${available} \
-            --arg interface "${interface}" \
-            --argjson classes "${classes_final}" \
-            --arg identifier "${identifier}" \
-            '{  parent: $parent,
-                version: $version,
-                available: $available,
-                interface: $interface,
-                classes: $classes,
-                identifier: $identifier}' )
-
-if [[ ! -z ${product} ]]
+########
+## If this is an update, we need to compare the data with the existing peripheral first
+########
+if [ -z $check_for_update ]
 then
-    name="${product}"
-    json=$(add_string_json "${json}" "product" "${product}")
-else
-    if [[ ! -z ${description} ]]
+    # This is a new peripheral. Create the payload and POST
+    json=$( jq -n \
+                --arg parent "${nb_id}" \
+                --argjson version ${nb_version} \
+                --argjson available ${available} \
+                --arg interface "${interface}" \
+                --argjson classes "${classes_final}" \
+                --arg identifier "${identifier}" \
+                '{  parent: $parent,
+                    version: $version,
+                    available: $available,
+                    interface: $interface,
+                    classes: $classes,
+                    identifier: $identifier}' )
+
+    if [[ ! -z ${product} ]]
     then
-        name=${description}
-        json=$(add_string_json "${json}" "description" "${description}")
-        json=$(add_string_json "${json}" "name" "${name}")
+        name="${product}"
+        json=$(add_string_json "${json}" "product" "${product}")
+    else
+        if [[ ! -z ${description} ]]
+        then
+            name=${description}
+            json=$(add_string_json "${json}" "description" "${description}")
+            json=$(add_string_json "${json}" "name" "${name}")
+        fi
     fi
+
+    if [[ ! -z ${vendor} ]]
+    then
+        json=$(add_string_json "${json}" "vendor" "${vendor}")
+    fi
+
+    if [[ ! -z ${device} ]]
+    then
+        json=$(add_string_json "${json}" "device-path" "${device}")
+    fi
+
+    if [[ ! -z ${video_device} ]]
+    then
+        json=$(add_string_json "${json}" "video-device" "${video_device}")
+    fi
+
+    if [[ ! -z ${device_serial} ]]
+    then
+        json=$(add_string_json "${json}" "serial-number" "${device_serial}")
+    fi
+
+    echo "INFO: posting new peripheral to Nuvla: ${json}"
+
+    (id=$(nuvla-client-post "nuvlabox-peripheral" "${json}") && \
+        nuvla_id=$(echo "${id}" | awk -F' ' '{print $NF}') && \
+        echo ${json} | jq --arg id "${nuvla_id}" '. + {id: $id}' > ${nuvlabox_peripheral_filename} && \
+        echo "INFO: successfully registered peripheral ${identifier}" ) || echo "ERR: could not register new USB device ${identifier}!"
+
+else
+    # Parameters that need to be compared:
+    #
 fi
 
-if [[ ! -z ${vendor} ]]
-then
-    json=$(add_string_json "${json}" "vendor" "${vendor}")
-fi
 
-if [[ ! -z ${device} ]]
-then
-    json=$(add_string_json "${json}" "device-path" "${device}")
-fi
-
-if [[ ! -z ${video_device} ]]
-then
-    json=$(add_string_json "${json}" "video-device" "${video_device}")
-fi
-
-if [[ ! -z ${device_serial} ]]
-then
-    json=$(add_string_json "${json}" "serial-number" "${device_serial}")
-fi
-
-echo "INFO: posting new peripheral to Nuvla: ${json}"
-
-(id=$(nuvla-client-post "nuvlabox-peripheral" "${json}") && \
-    nuvla_id=$(echo "${id}" | awk -F' ' '{print $NF}') && \
-    echo ${json} | jq --arg id "${nuvla_id}" '. + {id: $id}' > ${nuvlabox_peripheral_filename} && \
-    echo "INFO: successfully registered peripheral ${identifier}" ) || echo "ERR: could not register new USB device ${identifier}!"
